name = "Hpstr"
license = "MIT"
licenselink = "https://github.com/mauricius/hpstr-hugo-theme/blob/master/LICENSE.md"
description = "A Hugo port of the HPSTR theme by Michael Rose (mmistakes)"
homepage = "https://github.com/mauricius/hpstr-hugo-theme"
tags = ["responsive", "blog"]
features = ["comments", "scss", "menu"]

[author]
  name = "Maurizio Bonani"
  homepage = ""

# If porting an existing theme
[original]
  name = "Durand D'souza"
  homepage = "https://dldx.github.io/hpstr-hugo-theme/"
  repo = "https://dldx.github.io/hpstr-hugo-theme/"
